[WIP] JOSS paper revisions work
pysal/spopt pull request #200
Opened 2021-10-26 00:26 UTC by jGaboardi

*Starting to address #196.*

This PR starts the updates to the JOSS paper that incorporates the locate module.

2021-10-29 22:40 UTC, jGaboardi commented
I plan to go ahead with a release, which will be the baseline for our submission, this weekend after implementing the text update in the PR. If there are any detractors, speak now.

2021-10-31 15:50 UTC, gegen07 requested changes

2021-10-31 15:50 UTC, gegen07 commented on paper/paper.md
> +![The solution of MCLP in a case of siting 4 facilities using 5 kilometers as the maximum service distance between facilities and demands.\label{fig: mclp}](figs/mclp.png)
I'm reviewing the commit and found one issue.
- The image is not in `figs/`. It is giving an error when rendering the `.md` file.

2021-11-02 14:53 UTC, jGaboardi commented
Tie in with #203

2021-11-03 00:21 UTC, gegen07 approved these changes
LGTM

2021-11-03 00:22 UTC, merged