Facility capacity for LSCP
pysal/spopt pull request #273
Opened 2022-09-08 18:01 UTC by erinrolson

Implements facility capacity constraint for solving LSCP

2022-09-08 19:15 UTC, erinrolson commented on notebooks/lscp_capacity.ipynb
> +    "This tutorial solves LSCP using `spopt.locate.coverage.LSCP` instance that depends on a array 2D representing the costs between facilities candidate sites and demand points. For that it uses a l
Update intro with new description and reference/display new capacity formulation

2022-12-07 15:13 UTC, jGaboardi commented
@qszhao

2022-12-11 23:34 UTC, jGaboardi commented
@ljwolf conflicts were minor and now are resolved.

2022-12-14 15:54 UTC, ljwolf requested changes
I have one suggestion on the error warning, and would also suggest a bit more narrative in the example notebook. But, I'll need to commit that separately from this review.

2022-12-14 15:54 UTC, ljwolf commented on spopt/locate/base.py
> +                "before setting constraints must set facility variable and demand quantity variable"  # might want to update this message later
```suggestion
"The facility variable and demand quantity variable most both be set in order to add a client demand satisfaction constraint."
```

2022-12-14 16:21 UTC, ljwolf commented
OK, I've updated the notebook wording. I will merge once the tests pass.

2022-12-14 16:23 UTC, jGaboardi approved these changes

2022-12-14 16:29 UTC, ljwolf commented
Hmm, I missed that for sure. I think that the notebook serves as a user test, and the existing option passing is tested already. What's not tested is the more finicky stuff, like argument typing and things... I think it's OK here because the functionality is completely checked by the notebook, but I wouldn't want this to justify future code without tests!

2022-12-14 16:29 UTC, merged

2022-12-14 21:03 UTC, jGaboardi commented
> I think that the notebook serves as a user test, and the existing option passing is tested already. What's not tested is the more finicky stuff, like argument typing and things... I think it's OK here because the functionality is completely checked by the notebook, but I wouldn't want this to justify future code without tests!

My thoughts exactly. I will look into adding to @erinrolson's excellent contribution by doing a thorough doc review, adding tests, and probably adding some spice to the notebook. Hopefully I can get to this in the next couple weeks so we can include in the coming meta release.